"""Generate the shared font assets from the three bundled OFL faces.

The bake reads glyph outlines straight from the TTFs, but the browser cannot:
it has to lay the same text out on the same frame edge, at the same fitted size,
and draw the same outlines, without shipping a font parser or a boolean engine.
So this script distils each face into two JSON files:

``<face>.metrics.json``
    Per codepoint: the advance width, the dominant stroke width, the narrowest
    counter and the ink extents, all in FONT UNITS.  This is what
    ``transform.py`` / ``transform.ts`` compute the layout, the auto-fit and the
    printability refusal from, so both sides read exactly the same numbers.

``<face>.glyphs.json``
    The flattened contours of every supported glyph, in font units, with
    counters marked as holes.  Only the preview needs them (the bake flattens
    from the TTF at the real printed size), so this file is written into
    ``apps/web/`` only.

Both metrics files are written TWICE, byte for byte identically: once into
``apps/web/lib/fonts/`` for the browser and once into ``services/bake/app/fonts/``
for the service, so neither tree has to reach into the other at runtime and
``tests/test_lettering.py`` can assert the two copies - and the TTFs they came
from - still agree.

Run it from the repo root::

    cd services/bake && uv run python scripts/gen_font_assets.py

It is deterministic: re-running it on an unchanged font tree rewrites identical
bytes.  Every number is produced by :mod:`app.geom.lettering`, which is the same
code the bake cuts with.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
SERVICE_ROOT = Path(__file__).resolve().parents[1]
if str(SERVICE_ROOT) not in sys.path:  # so `python scripts/gen_font_assets.py` works
    sys.path.insert(0, str(SERVICE_ROOT))

from app.geom import lettering as L  # noqa: E402  (after the sys.path fix)

WEB_FONT_DIR = REPO_ROOT / "apps" / "web" / "lib" / "fonts"
BAKE_FONT_DIR = SERVICE_ROOT / "app" / "fonts"

#: Decimal places every measured font-unit quantity is rounded to.  Font units
#: are integers to begin with; the measurements are continuous, and three
#: decimals is 1/1000 of a unit, i.e. ~5 nanometres of print.
ROUND = 3

_COMMENT = (
    "GENERATED by services/bake/scripts/gen_font_assets.py from the bundled OFL "
    "font. Do not hand-edit: regenerate with "
    "`cd services/bake && uv run python scripts/gen_font_assets.py`. All lengths "
    "are FONT UNITS (units_per_em per em)."
)


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def font_version(face: L.Face) -> str:
    """The face's own version string, for the provenance record."""
    from fontTools.ttLib import TTFont

    font = TTFont(str(face.path), lazy=True)
    name = font["name"]
    for record in name.names:
        if record.nameID == 5:
            try:
                return str(record.toUnicode()).strip()
            except Exception:  # pragma: no cover - malformed name record
                continue
    return ""  # pragma: no cover - every shipped face has one


def build_metrics(face_name: str) -> dict[str, Any]:
    face = L.load_face(face_name)
    tolerance = L.flatten_tolerance_units(face, L.GLYPH_ASSET_SIZE_MM)
    glyphs: dict[str, Any] = {}
    for cp in L.SUPPORTED_CODEPOINTS:
        ch = chr(cp)
        if face.glyph_name(ch) is None:
            continue
        geom = L.glyph_polygon_units(face, ch, tolerance)
        if geom is None or geom.is_empty:
            bounds = (0.0, 0.0, 0.0, 0.0)
            stem = 0.0
            counter = None
        else:
            bounds = geom.bounds
            stem = L.glyph_stem_units(geom, face.upem)
            counter = L.glyph_counter_units(geom)
        glyphs[str(cp)] = {
            "adv": L.advance_units(face, ch),
            "stem": round(float(stem), ROUND),
            "counter": None if counter is None else round(float(counter), ROUND),
            "top": round(float(bounds[3]), ROUND),
            "bot": round(float(bounds[1]), ROUND),
            # Ink extents across the advance: the two of them are what the
            # shared math measures the GAP between two adjacent letters with,
            # and that gap is the ridge of lip that has to survive an engraving.
            "left": round(float(bounds[0]), ROUND),
            "right": round(float(bounds[2]), ROUND),
        }
    out = {
        "_comment": _COMMENT,
        "version": font_version(face),
        "sha256": sha256_of(face.path),
        "glyph_asset_size_mm": L.GLYPH_ASSET_SIZE_MM,
        "flatten_tolerance_mm": L.FLATTEN_TOLERANCE_MM,
        "stem_area_ratio": L.STEM_AREA_RATIO,
    }
    out.update(L.face_metrics(face_name))
    out["glyphs"] = glyphs
    return out


def build_glyph_outlines(face_name: str) -> dict[str, Any]:
    face = L.load_face(face_name)
    tolerance = L.flatten_tolerance_units(face, L.GLYPH_ASSET_SIZE_MM)
    glyphs: dict[str, Any] = {}
    for cp in L.SUPPORTED_CODEPOINTS:
        ch = chr(cp)
        if face.glyph_name(ch) is None:
            continue
        glyphs[str(cp)] = [
            {
                "shell": [
                    [round(x, ROUND), round(y, ROUND)] for x, y in part["shell"]
                ],
                "holes": [
                    [[round(x, ROUND), round(y, ROUND)] for x, y in hole]
                    for hole in part["holes"]
                ],
            }
            for part in glyph_parts(face, ch, tolerance)
        ]
    return {
        "_comment": _COMMENT,
        "face": face.name,
        "file": face.path.name,
        "units_per_em": face.upem,
        "glyph_asset_size_mm": L.GLYPH_ASSET_SIZE_MM,
        "flatten_tolerance_mm": L.FLATTEN_TOLERANCE_MM,
        "glyphs": glyphs,
    }


def glyph_parts(face: L.Face, ch: str, tolerance: float) -> list[dict[str, Any]]:
    """One glyph as ``[{shell, holes}, ...]`` rings in font units.

    Exported (rather than inlined) because ``tests/test_lettering.py`` asserts
    that the committed asset is exactly what this function produces today.
    """
    from app.geom import thicken

    geom = L.glyph_polygon_units(face, ch, tolerance)
    if geom is None or geom.is_empty:
        return []
    parts = []
    for poly in thicken.explode(geom):
        parts.append(
            {
                "shell": [(float(x), float(y)) for x, y in poly.exterior.coords[:-1]],
                "holes": [
                    [(float(x), float(y)) for x, y in ring.coords[:-1]]
                    for ring in poly.interiors
                ],
            }
        )
    return parts


def write_json(path: Path, payload: dict[str, Any]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=1, sort_keys=False, ensure_ascii=True) + "\n"
    path.write_text(text, encoding="utf-8")
    return len(text.encode("utf-8"))


#: Where the browser-side licence copies live.  The OFL requires its text to
#: travel with the font software, and `<face>.glyphs.json` IS font software -
#: 959 KiB of outlines extracted from the three TTFs, served to every visitor
#: (v2-03 audit, finding 5).  Copying them here from the one authoritative copy
#: beside each TTF means a font swap updates the licence in the same run.
WEB_LICENCE_DIR = REPO_ROOT / "apps" / "web" / "licences"

#: face key -> the committed licence file name in `apps/web/licences/`.
LICENCE_NAMES = {
    "sans": "OFL-Inter.txt",
    "serif": "OFL-Source-Serif-4.txt",
    "mono": "OFL-JetBrains-Mono.txt",
}


def copy_licence(face_name: str) -> int:
    source = BAKE_FONT_DIR / face_name / "OFL.txt"
    text = source.read_text(encoding="utf-8")
    target = WEB_LICENCE_DIR / LICENCE_NAMES[face_name]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8", newline="\n")
    return len(text.encode("utf-8"))


def main() -> int:
    for face_name in L.FACE_FILES:
        metrics = build_metrics(face_name)
        outlines = build_glyph_outlines(face_name)
        a = write_json(WEB_FONT_DIR / f"{face_name}.metrics.json", metrics)
        b = write_json(BAKE_FONT_DIR / f"{face_name}.metrics.json", metrics)
        c = write_json(WEB_FONT_DIR / f"{face_name}.glyphs.json", outlines)
        copy_licence(face_name)
        print(
            f"{face_name:5s} {metrics['file']:28s} {len(metrics['glyphs']):3d} glyphs  "
            f"metrics {a / 1024:6.1f} KiB (x2, {a == b}) outlines {c / 1024:7.1f} KiB"
        )
    return 0


if __name__ == "__main__":  # pragma: no cover - a script
    raise SystemExit(main())
