"""FrameCraft bake-service CLI.

Usage::

    uv run python -m app.cli refresh-fixtures [--preset ID ...] [--if-missing]
    uv run python -m app.cli scene --preset chicago-loop [--out FILE]
    uv run python -m app.cli scene --lat 41.88 --lon -87.62 --radius 900 [--rotation 0]

Structure: every subcommand is registered by its own ``_add_<name>`` function
that attaches a ``handler`` default, and ``main`` just dispatches.  Later phases
add ``bake`` (mesh-bake) and ``validate`` (qa-gate) by writing one more
``_add_*`` function and one line in :func:`build_parser` - nothing else here
needs to change.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

from app.contracts import SceneRequest
from app.ingest import normalize, overpass, presets

FIXTURES_DIR = overpass.FIXTURES_DIR
PRESETS_INDEX = FIXTURES_DIR / "presets-index.json"
_SHA1_FIXTURE_RE = re.compile(r"^[0-9a-f]{40}\.json$")

#: Courtesy pause between preset fetches, per the Overpass usage policy.
REFRESH_PAUSE_S = 5.0


# ---------------------------------------------------------------------------
# refresh-fixtures
# ---------------------------------------------------------------------------


def _write_presets_index(entries: list[dict[str, Any]]) -> None:
    payload = {
        "note": (
            "Generated by `python -m app.cli refresh-fixtures`. Maps each preset to its "
            "raw Overpass fixture, which is named after the sha1 of the query text (03)."
        ),
        "attribution": "© OpenStreetMap contributors",
        "endpoint": overpass.PRIMARY_ENDPOINT,
        "presets": entries,
    }
    PRESETS_INDEX.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )


def _index_entry(
    preset: presets.Preset,
    raw: dict[str, Any],
    path: Path,
    fetched_at: str | None = None,
) -> dict[str, Any]:
    """One presets-index.json row. ``fetched_at`` is carried over for a fixture
    that was skipped rather than re-fetched, so the timestamp never lies."""
    return {
        "preset_id": preset.id,
        "label": preset.label,
        "request": preset.request().model_dump(mode="json"),
        "fixture_file": path.name,
        "fetched_at": fetched_at or datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "element_count": len(raw.get("elements", [])),
        "bytes": path.stat().st_size if path.is_file() else 0,
    }


def cmd_refresh_fixtures(args: argparse.Namespace) -> int:
    """Re-fetch the raw Overpass response behind each preset and rewrite the index."""
    selected = list(presets.PRESETS)
    if args.preset:
        unknown = [p for p in args.preset if p not in presets.PRESETS_BY_ID]
        if unknown:
            print(f"unknown preset(s): {', '.join(unknown)}", file=sys.stderr)
            return 2
        selected = [presets.PRESETS_BY_ID[p] for p in args.preset]

    previous: dict[str, dict[str, Any]] = {}
    if PRESETS_INDEX.is_file():
        try:
            for entry in json.loads(PRESETS_INDEX.read_text(encoding="utf-8"))["presets"]:
                previous[entry["preset_id"]] = entry
        except (ValueError, KeyError):
            previous = {}

    entries: dict[str, dict[str, Any]] = dict(previous)
    failures = 0
    for i, preset in enumerate(selected):
        request = preset.request()
        query = overpass.build_query(request)
        path = overpass.fixture_path(query)
        if args.if_missing and path.is_file():
            raw = overpass.read_fixture(path)
            remark = overpass.fatal_remark(raw)
            if remark is None:
                print(f"{preset.id}: cached ({path.name}), skipping")
                keep = previous.get(preset.id, {})
                fetched_at = (
                    keep.get("fetched_at") if keep.get("fixture_file") == path.name else None
                )
                entries[preset.id] = _index_entry(preset, raw, path, fetched_at)
                continue
            # a cached Overpass error body is not a fixture; fetch it again
            print(f"{preset.id}: cached {path.name} is a server error ({remark}), re-fetching")
        if i and not args.if_missing:
            time.sleep(REFRESH_PAUSE_S)
        print(f"{preset.id}: fetching {path.name} ...", flush=True)
        try:
            raw = overpass.fetch_and_cache(request)
        except overpass.OverpassError as exc:
            failures += 1
            print(f"{preset.id}: FAILED: {exc}", file=sys.stderr)
            continue
        entries[preset.id] = _index_entry(preset, raw, path)
        size_mb = path.stat().st_size / (1024 * 1024)
        print(f"{preset.id}: {entries[preset.id]['element_count']} elements, {size_mb:.1f} MB")

    ordered = [entries[p.id] for p in presets.PRESETS if p.id in entries]
    _write_presets_index(ordered)

    if len(ordered) == len(presets.PRESETS) and not args.keep_stale:
        current = {e["fixture_file"] for e in ordered}
        for stale in sorted(FIXTURES_DIR.glob("*.json")):
            if _SHA1_FIXTURE_RE.match(stale.name) and stale.name not in current:
                stale.unlink()
                print(f"removed stale fixture {stale.name}")

    return 1 if failures else 0


def _add_refresh_fixtures(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "refresh-fixtures",
        help="re-fetch the six preset Overpass fixtures (the only command that uses the network)",
    )
    p.add_argument("--preset", action="append", help="refresh only this preset id (repeatable)")
    p.add_argument(
        "--if-missing",
        action="store_true",
        help="only fetch presets that have no cached fixture yet",
    )
    p.add_argument(
        "--keep-stale",
        action="store_true",
        help="keep sha1-named fixtures that no preset points at any more",
    )
    p.set_defaults(handler=cmd_refresh_fixtures)


# ---------------------------------------------------------------------------
# scene
# ---------------------------------------------------------------------------


def _request_from_args(args: argparse.Namespace) -> SceneRequest:
    if args.preset:
        preset = presets.get_preset(args.preset)
        if preset is None:
            raise SystemExit(f"unknown preset: {args.preset}")
        return preset.request()
    if args.lat is None or args.lon is None:
        raise SystemExit("scene needs either --preset or --lat/--lon")
    return SceneRequest(
        lat=args.lat,
        lon=args.lon,
        radius_m=args.radius,
        rotation_deg=args.rotation,
        preset_id=None,
    )


def cmd_scene(args: argparse.Namespace) -> int:
    """Print the SceneGraph for a preset (or an ad-hoc location) as JSON."""
    request = _request_from_args(args)
    raw = overpass.load_raw(request, allow_network=not (args.offline or bool(request.preset_id)))
    scene = normalize.build_scene(raw, request)
    text = json.dumps(scene.model_dump(mode="json"), indent=None if args.compact else 2)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text + "\n", encoding="utf-8", newline="\n")
        stats = scene.stats
        print(
            f"wrote {out} - {stats.building_count} buildings, coverage={stats.coverage}, "
            f"height_tag_ratio={stats.height_tag_ratio:.3f}, roads={len(scene.roads)}, "
            f"water={len(scene.water)}, green={len(scene.green)}, trees={len(scene.trees)}"
        )
    else:
        print(text)
    return 0


def _add_scene(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser("scene", help="build a SceneGraph from a fixture (or Overpass) and print it")
    p.add_argument("--preset", help="preset id, e.g. chicago-loop (never uses the network)")
    p.add_argument("--lat", type=float)
    p.add_argument("--lon", type=float)
    p.add_argument("--radius", type=float, default=presets.PRESET_RADIUS_M, dest="radius")
    p.add_argument("--rotation", type=float, default=0.0, dest="rotation")
    p.add_argument("--out", help="write to this file instead of stdout")
    p.add_argument("--compact", action="store_true", help="one-line JSON")
    p.add_argument("--offline", action="store_true", help="fail instead of fetching on a cache miss")
    p.set_defaults(handler=cmd_scene)


# ---------------------------------------------------------------------------
# bake  (mesh-bake, P3)
# ---------------------------------------------------------------------------


def _print_params_from_args(args: argparse.Namespace) -> "PrintParams":
    """``--params`` is a JSON object, or ``@file.json``; missing keys default."""
    from app.contracts import PrintParams

    raw = getattr(args, "params", None)
    if not raw:
        return PrintParams()
    if raw.startswith("@"):
        raw = Path(raw[1:]).read_text(encoding="utf-8")
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise SystemExit("--params must be a JSON object")
    return PrintParams(**data)


def cmd_bake(args: argparse.Namespace) -> int:
    """Run the whole 04 pipeline synchronously and write every artifact."""
    from app import bake as bake_pipeline

    request = _request_from_args(args)
    params = _print_params_from_args(args)
    out = Path(args.out).resolve()
    if out.suffix.lower() not in (".3mf", ".stl"):
        raise SystemExit("--out must end in .3mf or .stl")

    started = time.perf_counter()
    raw = overpass.load_raw(request, allow_network=not (args.offline or bool(request.preset_id)))
    scene = normalize.build_scene(raw, request)
    print(
        f"scene: {scene.stats.building_count} buildings, coverage={scene.stats.coverage}, "
        f"roads={len(scene.roads)}, water={len(scene.water)}, green={len(scene.green)}, "
        f"trees={len(scene.trees)}"
    )

    def progress(stage: str, value: float) -> None:
        print(f"  [{value:4.0%}] {stage}", flush=True)

    try:
        result = bake_pipeline.run_pipeline(
            scene,
            request,
            params,
            job_id=out.stem,
            out_dir=out.parent,
            stem=out.stem,
            progress=progress,
        )
    except bake_pipeline.BakeError as exc:
        print(f"bake refused: {exc}", file=sys.stderr)
        return 2

    elapsed = time.perf_counter() - started
    stats = result.result.stats
    print()
    print(result.report.to_table())
    print()
    if stats is not None:
        print(
            f"triangles      {stats.triangles:,}\n"
            f"volume         {stats.volume_mm3:,.1f} mm^3\n"
            f"bounding box   {stats.bbox_mm[0]:.2f} x {stats.bbox_mm[1]:.2f} x "
            f"{stats.bbox_mm[2]:.2f} mm\n"
            f"filament       {stats.est_grams:.1f} g (ESTIMATE, 15% infill, 3 walls)\n"
            f"manifold       {'yes' if stats.is_manifold else 'no'}\n"
            f"min wall       {stats.min_wall_mm:.3f} mm (measured)"
        )
    for warning in result.result.warnings:
        print(f"warning: {warning}")
    for name, path in result.paths.items():
        print(f"{name:8s} {path}")
    print(f"bake time      {elapsed:.1f} s")
    if result.result.status != "done":
        print(f"FAILED: {result.result.error}", file=sys.stderr)
        if result.debug_dir is not None:
            print(f"intermediate solids: {result.debug_dir}", file=sys.stderr)
        return 1
    return 0


def _add_bake(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser("bake", help="run the printability pipeline and write .3mf/.stl/.json")
    p.add_argument("--preset", help="preset id, e.g. chicago-loop (never uses the network)")
    p.add_argument("--lat", type=float)
    p.add_argument("--lon", type=float)
    p.add_argument("--radius", type=float, default=presets.PRESET_RADIUS_M, dest="radius")
    p.add_argument("--rotation", type=float, default=0.0, dest="rotation")
    p.add_argument("--out", required=True, help="output path, e.g. ../../artifacts/chicago.3mf")
    p.add_argument("--params", help="PrintParams as JSON, or @file.json")
    p.add_argument("--offline", action="store_true", help="fail instead of fetching on a miss")
    p.set_defaults(handler=cmd_bake)


# ---------------------------------------------------------------------------
# validate  (mesh-bake, P3)
# ---------------------------------------------------------------------------


def _compact_pydantic_error(exc: Exception) -> str:
    """One line naming the offending fields, instead of pydantic's block.

    ``ValidationError`` is a fine thing to raise inside the service; printed at
    a CLI it is a traceback, and a traceback is not a validation verdict.
    """
    errors = getattr(exc, "errors", None)
    if not callable(errors):
        return str(exc)
    parts: list[str] = []
    for err in errors():
        loc = ".".join(str(p) for p in err.get("loc", ())) or "(root)"
        parts.append(f"{loc}: {err.get('msg', 'invalid')}")
    if not parts:
        return str(exc)
    return "; ".join(parts[:3]) + (f"; +{len(parts) - 3} more" if len(parts) > 3 else "")


def _ellipsis(text: str, width: int) -> str:
    """Trim a message to the report table's column without hiding the point."""
    return text if len(text) <= width else text[: width - 3] + "..."


def _cli_overrides(plate_mm: float | None, nozzle_mm: float | None) -> dict[str, Any]:
    overrides: dict[str, Any] = {}
    if plate_mm is not None:
        overrides["plate_mm"] = plate_mm
    if nozzle_mm is not None:
        overrides["nozzle_mm"] = nozzle_mm
    return overrides


def _params_from_sidecar(
    path: Path, plate_mm: float | None, nozzle_mm: float | None
) -> tuple["PrintParams", str, str | None]:
    """PrintParams for a file, plus where they came from and what went wrong.

    Order of precedence: the file's ``<stem>.json`` bake sidecar, then the
    ``--plate-mm`` / ``--nozzle-mm`` overrides on top of it, then the contract
    defaults for everything unset.

    A sidecar that EXISTS but cannot be used - unreadable, not JSON, carrying no
    ``print_params`` object, or carrying values the FROZEN contract rejects - is
    neither fatal nor silently ignored.  It comes back as the third element so
    ``cmd_validate`` can print a ``sidecar_params`` FAIL row and still judge the
    mesh against whatever the caller named on the command line; before this the
    contract's own bounds check reached the terminal as a pydantic traceback,
    and a file with a mis-recorded plate size could not be validated at all.
    """
    from app.contracts import PrintParams

    overrides = _cli_overrides(plate_mm, nozzle_mm)
    sidecar = path.with_suffix(".json")
    fallback_source = "command line" if overrides else "defaults"

    def _fallback(reason: str) -> tuple[PrintParams, str, str]:
        # The sidecar contributes nothing; the caller's overrides still do.
        return PrintParams(**overrides), fallback_source, reason

    if not sidecar.is_file():
        return PrintParams(**overrides), fallback_source, None

    try:
        payload = json.loads(sidecar.read_text(encoding="utf-8"))
    except OSError as exc:
        return _fallback(f"cannot read {sidecar.name} ({exc.strerror or exc})")
    except ValueError as exc:
        return _fallback(f"{sidecar.name} is not valid JSON ({exc})")
    if not isinstance(payload, dict) or not isinstance(payload.get("print_params"), dict):
        return _fallback(f"{sidecar.name} carries no print_params object")

    data = dict(payload["print_params"])
    data.update(overrides)
    try:
        params = PrintParams(**data)
    except Exception as exc:  # pydantic.ValidationError, and anything like it
        return _fallback(_compact_pydantic_error(exc))
    source = f"sidecar {sidecar.name}" + (" + command line" if overrides else "")
    return params, source, None


def _index_stl_triangle_soup(mesh: "trimesh.Trimesh") -> tuple["trimesh.Trimesh", int]:
    """Weld the *exactly* coincident vertices of an STL triangle soup.

    A binary STL stores three free-floating vertices per facet and has no index,
    so ``trimesh.load(..., process=False)`` hands back 3F vertices for F faces
    and every edge is "shared by one face": manifold, watertight and
    self_intersection all fail on a file the 3MF of the same model passes.  The
    weld here is bitwise (``np.unique`` on the float32 rows the file itself
    stores), never a tolerance pass: it re-indexes the soup and cannot close a
    real crack, so the topology this command exists to judge is unchanged.
    """
    import numpy as np
    import trimesh

    vertices, inverse = np.unique(np.asarray(mesh.vertices), axis=0, return_inverse=True)
    removed = len(mesh.vertices) - len(vertices)
    if removed <= 0:
        return mesh, 0
    faces = np.asarray(inverse).reshape(-1)[np.asarray(mesh.faces)]
    welded = trimesh.Trimesh(vertices=vertices, faces=faces, process=False, validate=False)
    return welded, removed


def _single_body_check(mesh: "trimesh.Trimesh") -> "Check":
    """01/A6: the file must open in a slicer as ONE object, not one plus debris.

    04 stage 4's ``watertight`` row deliberately tolerates several bodies - its
    Euler test is ``even and <= 2 * body_count`` - because it judges an
    arbitrary mesh.  A finished FrameCraft plate is not arbitrary: it is one
    connected solid sitting on the bed, and a floating island (a stray cube at
    z = 30, a shell the boolean left behind) is exactly the failure a slicer
    surfaces to the user.  ``3mf_objects`` and ``3mf_build_items`` count XML
    elements, so a second body written into the *same* ``<object>`` slips past
    both of them; this row counts shells.  It runs for ``.stl`` as well, which
    has no container rows at all.
    """
    from app.validate.checks import Check, body_count

    bodies = body_count(mesh)
    return Check(
        name="bodies",
        passed=bodies == 1,
        value=bodies,
        threshold=1,
        message=(
            "one connected solid, so a slicer shows a single object"
            if bodies == 1
            else f"{bodies} disconnected bodies; a slicer would show {bodies} objects "
            "(a floating island or leftover boolean debris)"
        ),
    )


def _threemf_structure_checks(path: Path, mesh: "trimesh.Trimesh") -> list["Check"]:
    """Container checks for a ``.3mf``, on top of 04 stage 4's mesh validators.

    04 stage 3 specifies the package a bake must write and A6 needs a slicer to
    open it as ONE object sitting on the bed, so ``make validate`` judges the
    file as well as the mesh: the three OPC parts exist, the model is declared
    in millimetres, there is exactly one ``<object>`` and exactly one build
    ``<item>`` (two would make a slicer show two bodies), the ``Description``
    metadata carries the OSM attribution the licence requires, and the vertex /
    triangle counts the XML declares are exactly what the loader handed back
    (an object no build item references, or a loader that silently welded, both
    show up here).
    """
    import xml.etree.ElementTree as ET
    import zipfile

    from app.export import mf3
    from app.validate.checks import Check

    required = (mf3.CONTENT_TYPES_PART, mf3.RELS_PART, mf3.MODEL_PART)
    threshold_parts = ", ".join(required)
    try:
        with zipfile.ZipFile(path) as zf:
            names = zf.namelist()
            payload = zf.read(mf3.MODEL_PART) if mf3.MODEL_PART in names else b""
    except (zipfile.BadZipFile, OSError, KeyError) as exc:
        return [
            Check(
                name="3mf_parts",
                passed=False,
                value=f"unreadable: {type(exc).__name__}",
                threshold=threshold_parts,
                message=f"{path.name} is not a readable OPC (zip) package: {exc}",
            )
        ]

    missing = [part for part in required if part not in names]
    checks = [
        Check(
            name="3mf_parts",
            passed=not missing,
            value=f"{len(names)} parts" + (f", missing {', '.join(missing)}" if missing else ""),
            threshold=threshold_parts,
            message=(
                f"missing required 3MF part(s): {', '.join(missing)}"
                if missing
                else "[Content_Types].xml, _rels/.rels and 3D/3dmodel.model are all present"
            ),
        )
    ]
    if not payload:
        return checks

    # Same hardening as mf3.read_metadata: a 3MF has no legitimate use for a DTD.
    if b"<!DOCTYPE" in payload[:4096] or b"<!ENTITY" in payload[:4096]:
        checks.append(
            Check(
                name="3mf_model_xml",
                passed=False,
                value="declares a DTD",
                threshold="no DTD",
                message="the model part declares a DTD; refusing to parse it",
            )
        )
        return checks

    try:
        root = ET.fromstring(payload)
    except ET.ParseError as exc:
        checks.append(
            Check(
                name="3mf_model_xml",
                passed=False,
                value=f"unparseable: {exc}",
                threshold="well-formed XML",
                message=f"3D/3dmodel.model is not well-formed XML: {exc}",
            )
        )
        return checks

    ns = f"{{{mf3.CORE_NAMESPACE}}}"
    unit = root.get("unit")
    checks.append(
        Check(
            name="3mf_unit",
            passed=unit == "millimeter",
            value=unit or "-",
            threshold="millimeter",
            message=(
                "the model is declared in millimetres"
                if unit == "millimeter"
                else f'unit is {unit!r}; a FrameCraft plate is authored in millimetres'
            ),
        )
    )

    objects = root.findall(f".//{ns}object")
    checks.append(
        Check(
            name="3mf_objects",
            passed=len(objects) == 1,
            value=len(objects),
            threshold=1,
            message=(
                "exactly one <object>, so a slicer shows one body"
                if len(objects) == 1
                else f"{len(objects)} <object> elements; A6 needs exactly one"
            ),
        )
    )

    build = root.find(f"{ns}build")
    items = [] if build is None else build.findall(f"{ns}item")
    checks.append(
        Check(
            name="3mf_build_items",
            passed=len(items) == 1,
            value=len(items),
            threshold=1,
            message=(
                "exactly one <build><item>, placed once on the bed"
                if len(items) == 1
                else f"{len(items)} build items; A6 needs exactly one"
            ),
        )
    )

    description = ""
    for node in root.findall(f"{ns}metadata"):
        if node.get("name") == "Description":
            description = node.text or ""
    has_attribution = mf3.ATTRIBUTION in description
    checks.append(
        Check(
            name="3mf_attribution",
            passed=has_attribution,
            # Deliberately not the text itself: a Windows console codepage that
            # cannot encode "(c)" would turn printing the row into a crash.
            value=(
                f"present ({len(description)} chars)"
                if has_attribution
                else f"absent ({len(description)} chars of Description)"
            ),
            threshold="OSM attribution in Description",
            message=(
                "the OSM attribution travels with the file"
                if has_attribution
                else "Description metadata does not carry '© OpenStreetMap contributors'"
            ),
        )
    )

    xml_vertices = len(root.findall(f".//{ns}vertex"))
    xml_triangles = len(root.findall(f".//{ns}triangle"))
    mesh_counts = (
        f"mesh {len(mesh.vertices):,} v / {len(mesh.faces):,} t"
        if mesh is not None
        else "a loadable mesh"
    )
    counts_ok = mesh is not None and (
        xml_vertices == len(mesh.vertices) and xml_triangles == len(mesh.faces)
    )
    checks.append(
        Check(
            name="3mf_counts",
            passed=counts_ok,
            value=f"xml {xml_vertices:,} v / {xml_triangles:,} t",
            threshold=mesh_counts,
            message=(
                "every vertex and triangle the file declares is in the loaded mesh"
                if counts_ok
                else (
                    f"the XML declares {xml_vertices} vertices / {xml_triangles} triangles "
                    + (
                        f"but the loader produced {len(mesh.vertices)} / {len(mesh.faces)}"
                        if mesh is not None
                        else "but the file did not load as a triangle mesh at all"
                    )
                )
            ),
        )
    )
    return checks


def cmd_validate(args: argparse.Namespace) -> int:
    """Run the 04 stage 4 validators against a finished .3mf or .stl."""
    import trimesh

    from app.validate import checks as validators

    path = Path(args.file).resolve()
    if not path.is_file():
        print(f"no such file: {path}", file=sys.stderr)
        return 2

    # An override the contract itself rejects is a usage error, not a verdict
    # about the file: say so before spending anything on loading the mesh.
    from app.contracts import PrintParams

    try:
        PrintParams(**_cli_overrides(args.plate_mm, args.nozzle_mm))
    except Exception as exc:
        print(f"invalid override: {_compact_pydantic_error(exc)}", file=sys.stderr)
        return 2

    is_3mf = path.suffix.lower() == ".3mf"

    # process=False: trimesh's default load pass welds vertices within 1e-8 and
    # would "repair" the very topology this command exists to judge.  What is
    # validated has to be exactly what is in the file.
    load_error: str | None = None
    mesh: Any = None
    try:
        mesh = trimesh.load(path, force="mesh", process=False)
    except Exception as exc:  # a corrupt package must still print a table
        load_error = f"{type(exc).__name__}: {exc}"
    if not isinstance(mesh, trimesh.Trimesh) or len(mesh.faces) == 0:
        if not is_3mf:
            print(f"{path.name} does not contain a triangle mesh", file=sys.stderr)
            if load_error:
                print(load_error, file=sys.stderr)
            return 2
        # A .3mf that will not load is a container failure; say which part is
        # wrong instead of dumping a traceback.
        mesh = None
        print(f"file           {path}")
        print(f"load           FAILED ({load_error or 'no triangle mesh in the package'})")
        print()
        broken = validators.ValidationReport(checks=_threemf_structure_checks(path, None))
        print(broken.to_table())
        return 1

    welded = 0
    if path.suffix.lower() == ".stl":
        mesh, welded = _index_stl_triangle_soup(mesh)

    params, param_source, sidecar_error = _params_from_sidecar(
        path, args.plate_mm, args.nozzle_mm
    )
    print(f"file           {path}")
    print(f"parameters     {param_source}"
          f"  (plate {params.plate_mm:g} mm, nozzle {params.nozzle_mm:g} mm)")
    if sidecar_error is not None:
        print(f"sidecar        sidecar params invalid: {sidecar_error}")
    if welded:
        print(
            f"stl            indexed {welded:,} duplicate vertices (exact positions; "
            "a binary STL has no vertex index)"
        )
    print()
    report = validators.validate(mesh, params)
    if sidecar_error is not None:
        # The file's own record of how it was printed is broken, so every row
        # below it is being judged against parameters that may not be the ones
        # the bake used. That is a FAIL, not a footnote.
        report.checks.insert(
            0,
            validators.Check(
                name="sidecar_params",
                passed=False,
                value=_ellipsis(f"sidecar params invalid: {sidecar_error}", 64),
                threshold="PrintParams the contract accepts",
                message=(
                    f"sidecar params invalid: {sidecar_error}; "
                    f"the mesh below was judged against {param_source} "
                    f"(plate {params.plate_mm:g} mm, nozzle {params.nozzle_mm:g} mm)"
                ),
            ),
        )
    report.checks.append(_single_body_check(mesh))
    if is_3mf:
        # 04 stage 4 judges the mesh; these judge the package around it.
        report.checks.extend(_threemf_structure_checks(path, mesh))
    print(report.to_table())
    return 0 if report.passed else 1


def _add_validate(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser("validate", help="run the 04 printability validators on a .3mf or .stl")
    p.add_argument("file", help="path to a .3mf or .stl")
    p.add_argument("--plate-mm", type=float, dest="plate_mm", help="override the plate size")
    p.add_argument("--nozzle-mm", type=float, dest="nozzle_mm", help="override the nozzle size")
    p.set_defaults(handler=cmd_validate)


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="app.cli", description="FrameCraft bake-service CLI")
    sub = parser.add_subparsers(dest="command", required=True)
    _add_refresh_fixtures(sub)
    _add_scene(sub)
    _add_bake(sub)
    _add_validate(sub)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(list(argv) if argv is not None else None)
    try:
        return int(args.handler(args) or 0)
    except BrokenPipeError:  # `... | head` closed the pipe; not an error
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
